name: Cypress Web Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Run Tests
        run: npx cypress run
